# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 49d75d247ee9646ee1cc9e2c013912859e31defce3172b7f4e52dd9cc1e33acf39c8a35c89608a135bb6e8ddeb32339e89ddbcd2398f4fe010c562ab079d1e43

test:
  secret_key_base: d84e004226834f82fb66929a6f2ac7b467aa897ff827b8cd0f6d8b3805f11f339ac2e078632e9ee71f41d523f1d08357dd210e4e080832646d3dce72f4f0b9fd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
