# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

STEAM_WEB_API_KEY: '51EC3016597AB1EB1BC274E17432258F'
SECRET_TOKEN: '62e9c8c64b969773839129e05d6ec53e0ef2306f7258831e21c19cfb4dc2c74bb31d1e3ca94196f4120b72b406901798ad2e971516b38877eea73b64901836a7'

GOOGLE_CLIENT_ID: "872803402078-pd5jq5iufrdb5qin5pk3mohkrtq88pjq.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET: "UiKIXUBHzHgk9KsS7T_ujDoB"

maps:
  api_key: //maps.google.com/maps/api/js?key=AIzaSyDPyLaza4pTmIuuxKeZodgrmHOxUGRbrGA
  igdb: 'zrw3u5epljf332wimpj5dfajrk6uoa'
  secret: 'v3vq1sxljqm268grb7rh51o4188x83'
  access_token: 'Bearer id8usdz9rarc8xns7uqisgtwgn1bgb'