name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up dependecies
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.x
        nodejs-version: 10.x
        libsqlite3-dev-version: 3.x
    - name: Budler installation
      run: |
        pwd
        cd VGdatabase
        pwd
        gem install bundler
        gem install rails
        gem update --system
        sudo bundle install --jobs 4 --retry 3
        rails server
